### PR TITLE
Fixed redundant lastres config file creation

### PR DESCRIPTION
**Pull request by KerballOne**
Fixed redundant lastres config file creation and fixed nullexception bug

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Still broken.  I started with a new install, started the game with the release Anyres, got to the KSP
Exited, installed new version on top of it
Started game, went to KSC, toolbars are missing.  Also, clicking on the runway locked it up,

**Comment by KerballOne** [comment]
> Still broken. I started with a new install, started the game with the release Anyres, got to the KSP Exited, installed new version on top of it Started game, went to KSC, toolbars are missing. Also, clicking on the runway locked it up,

I am getting a different result.  I am starting with stock install with only a few mods.
I've previously seen that blank KSC (no toolbars, no other UI elements) before while testing.  It happens if the UI_Scale is set to 0 by something.
Can you check if that is happening in your settings.cfg?  

Oh, maybe it's the presence of config files that do not have the scale parameter.  They may need to be replaced or removed.  I may need to add code to check legacy config files.

I can reproduce the loss of KSC UI (toolbars and all other UI), if I manually load a legacy preset from the AnyRes window.  But the LastSetRes.cfg and the SPACECENTER.cfg files are created properly with the scale parameter.  So I am not able to reproduce exactly what you are getting.
I'll create error checking code to make sure it doesn't ever set UI to zero.

**Comment by KerballOne** [comment]
Updated code with a few error checks to make sure it doesn't get caught with 0 UI scale.

**Comment by linuxgurugamer** [comment]
I just merged this whole thing

**Comment by linuxgurugamer** [comment]
and released

**Pull request merged**
